# Generated by Django 4.2 on 2025-11-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_coupon_order_order_number_order_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='configurations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_AR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
