# Generated by Django 4.2 on 2025-10-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
