# Generated by Django 4.2 on 2025-11-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_product_configurations_product_is_ar_product_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.FileField(blank=True, null=True, upload_to='products/'),
        ),
    ]
